"""
Weekly Email Sender for Art Prize Application Strategy
매주 월요일 자동으로 application_strategy_2026.md를 이메일로 발송
"""

import smtplib
import os
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# === 설정 ===
SENDER_EMAIL = "erichoi815@gmail.com"
SENDER_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD", "")
RECIPIENT_EMAIL = "erichoi815@gmail.com"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MD_FILE = os.path.join(SCRIPT_DIR, "application_strategy_2026.md")


def read_strategy_file():
    with open(MD_FILE, "r", encoding="utf-8") as f:
        return f.read()


def send_email():
    if not SENDER_APP_PASSWORD:
        print("ERROR: GMAIL_APP_PASSWORD 환경변수가 설정되지 않았습니다.")
        print("설정 방법: set GMAIL_APP_PASSWORD=your_app_password")
        sys.exit(1)

    content = read_strategy_file()
    today = datetime.now().strftime("%Y-%m-%d")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[Art Prize 2026] 주간 지원 전략 업데이트 - {today}"
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECIPIENT_EMAIL

    # 텍스트 버전
    text_part = MIMEText(content, "plain", "utf-8")
    msg.attach(text_part)

    # HTML 버전 (마크다운을 간단한 HTML로 변환)
    html_content = content.replace("\n", "<br>\n")
    html_content = f"""
    <html>
    <body style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6;">
        <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
            🎨 Art Prize Application Strategy - Weekly Update
        </h2>
        <p style="color: #7f8c8d; font-size: 14px;">발송일: {today} (매주 월요일 자동 발송)</p>
        <hr>
        <pre style="white-space: pre-wrap; font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px;">{content}</pre>
        <hr>
        <p style="color: #95a5a6; font-size: 12px;">
            이 이메일은 자동으로 발송되었습니다.<br>
            Generated by AI Art Prize Application System
        </p>
    </body>
    </html>
    """
    html_part = MIMEText(html_content, "html", "utf-8")
    msg.attach(html_part)

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_APP_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        print(f"[{today}] 이메일 발송 성공! -> {RECIPIENT_EMAIL}")
    except smtplib.SMTPAuthenticationError:
        print("ERROR: Gmail 인증 실패. 앱 비밀번호를 확인해주세요.")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: 이메일 발송 실패 - {e}")
        sys.exit(1)


if __name__ == "__main__":
    send_email()
